<?php
/**
 * CmsBlock
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shopware Admin API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Admin API.  For a better overview, all CRUD-endpoints are hidden by default. If you want to show also CRUD-endpoints add the query parameter `type=jsonapi`.
 *
 * The version of the OpenAPI document: 6.4.8.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CmsBlock Class Doc Comment
 *
 * @category Class
 * @description Added since version: 6.0.0.0
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class CmsBlock implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CmsBlock';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'position' => 'int',
        'type' => 'string',
        'locked' => 'bool',
        'name' => 'string',
        'section_position' => 'string',
        'margin_top' => 'string',
        'margin_bottom' => 'string',
        'margin_left' => 'string',
        'margin_right' => 'string',
        'background_color' => 'string',
        'background_media_id' => 'string',
        'background_media_mode' => 'string',
        'css_class' => 'string',
        'section_id' => 'string',
        'custom_fields' => 'object',
        'version_id' => 'string',
        'cms_section_version_id' => 'string',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'section' => '\OpenAPI\Client\Model\CmsSection',
        'background_media' => '\OpenAPI\Client\Model\Media',
        'slots' => '\OpenAPI\Client\Model\CmsSlot'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'position' => 'int64',
        'type' => null,
        'locked' => null,
        'name' => null,
        'section_position' => null,
        'margin_top' => null,
        'margin_bottom' => null,
        'margin_left' => null,
        'margin_right' => null,
        'background_color' => null,
        'background_media_id' => null,
        'background_media_mode' => null,
        'css_class' => null,
        'section_id' => null,
        'custom_fields' => null,
        'version_id' => null,
        'cms_section_version_id' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'section' => null,
        'background_media' => null,
        'slots' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'position' => 'position',
        'type' => 'type',
        'locked' => 'locked',
        'name' => 'name',
        'section_position' => 'sectionPosition',
        'margin_top' => 'marginTop',
        'margin_bottom' => 'marginBottom',
        'margin_left' => 'marginLeft',
        'margin_right' => 'marginRight',
        'background_color' => 'backgroundColor',
        'background_media_id' => 'backgroundMediaId',
        'background_media_mode' => 'backgroundMediaMode',
        'css_class' => 'cssClass',
        'section_id' => 'sectionId',
        'custom_fields' => 'customFields',
        'version_id' => 'versionId',
        'cms_section_version_id' => 'cmsSectionVersionId',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt',
        'section' => 'section',
        'background_media' => 'backgroundMedia',
        'slots' => 'slots'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'position' => 'setPosition',
        'type' => 'setType',
        'locked' => 'setLocked',
        'name' => 'setName',
        'section_position' => 'setSectionPosition',
        'margin_top' => 'setMarginTop',
        'margin_bottom' => 'setMarginBottom',
        'margin_left' => 'setMarginLeft',
        'margin_right' => 'setMarginRight',
        'background_color' => 'setBackgroundColor',
        'background_media_id' => 'setBackgroundMediaId',
        'background_media_mode' => 'setBackgroundMediaMode',
        'css_class' => 'setCssClass',
        'section_id' => 'setSectionId',
        'custom_fields' => 'setCustomFields',
        'version_id' => 'setVersionId',
        'cms_section_version_id' => 'setCmsSectionVersionId',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'section' => 'setSection',
        'background_media' => 'setBackgroundMedia',
        'slots' => 'setSlots'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'position' => 'getPosition',
        'type' => 'getType',
        'locked' => 'getLocked',
        'name' => 'getName',
        'section_position' => 'getSectionPosition',
        'margin_top' => 'getMarginTop',
        'margin_bottom' => 'getMarginBottom',
        'margin_left' => 'getMarginLeft',
        'margin_right' => 'getMarginRight',
        'background_color' => 'getBackgroundColor',
        'background_media_id' => 'getBackgroundMediaId',
        'background_media_mode' => 'getBackgroundMediaMode',
        'css_class' => 'getCssClass',
        'section_id' => 'getSectionId',
        'custom_fields' => 'getCustomFields',
        'version_id' => 'getVersionId',
        'cms_section_version_id' => 'getCmsSectionVersionId',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'section' => 'getSection',
        'background_media' => 'getBackgroundMedia',
        'slots' => 'getSlots'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['position'] = $data['position'] ?? null;
        $this->container['type'] = $data['type'] ?? null;
        $this->container['locked'] = $data['locked'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['section_position'] = $data['section_position'] ?? null;
        $this->container['margin_top'] = $data['margin_top'] ?? null;
        $this->container['margin_bottom'] = $data['margin_bottom'] ?? null;
        $this->container['margin_left'] = $data['margin_left'] ?? null;
        $this->container['margin_right'] = $data['margin_right'] ?? null;
        $this->container['background_color'] = $data['background_color'] ?? null;
        $this->container['background_media_id'] = $data['background_media_id'] ?? null;
        $this->container['background_media_mode'] = $data['background_media_mode'] ?? null;
        $this->container['css_class'] = $data['css_class'] ?? null;
        $this->container['section_id'] = $data['section_id'] ?? null;
        $this->container['custom_fields'] = $data['custom_fields'] ?? null;
        $this->container['version_id'] = $data['version_id'] ?? null;
        $this->container['cms_section_version_id'] = $data['cms_section_version_id'] ?? null;
        $this->container['created_at'] = $data['created_at'] ?? null;
        $this->container['updated_at'] = $data['updated_at'] ?? null;
        $this->container['section'] = $data['section'] ?? null;
        $this->container['background_media'] = $data['background_media'] ?? null;
        $this->container['slots'] = $data['slots'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['id']) && !preg_match("/^[0-9a-f]{32}$/", $this->container['id'])) {
            $invalidProperties[] = "invalid value for 'id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if ($this->container['position'] === null) {
            $invalidProperties[] = "'position' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if (!is_null($this->container['background_media_id']) && !preg_match("/^[0-9a-f]{32}$/", $this->container['background_media_id'])) {
            $invalidProperties[] = "invalid value for 'background_media_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if ($this->container['section_id'] === null) {
            $invalidProperties[] = "'section_id' can't be null";
        }
        if (!preg_match("/^[0-9a-f]{32}$/", $this->container['section_id'])) {
            $invalidProperties[] = "invalid value for 'section_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if (!is_null($this->container['version_id']) && !preg_match("/^[0-9a-f]{32}$/", $this->container['version_id'])) {
            $invalidProperties[] = "invalid value for 'version_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if (!is_null($this->container['cms_section_version_id']) && !preg_match("/^[0-9a-f]{32}$/", $this->container['cms_section_version_id'])) {
            $invalidProperties[] = "invalid value for 'cms_section_version_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {

        if (!is_null($id) && (!preg_match("/^[0-9a-f]{32}$/", $id))) {
            throw new \InvalidArgumentException("invalid value for $id when calling CmsBlock., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets position
     *
     * @return int
     */
    public function getPosition()
    {
        return $this->container['position'];
    }

    /**
     * Sets position
     *
     * @param int $position position
     *
     * @return self
     */
    public function setPosition($position)
    {
        $this->container['position'] = $position;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return self
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets locked
     *
     * @return bool|null
     */
    public function getLocked()
    {
        return $this->container['locked'];
    }

    /**
     * Sets locked
     *
     * @param bool|null $locked locked
     *
     * @return self
     */
    public function setLocked($locked)
    {
        $this->container['locked'] = $locked;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets section_position
     *
     * @return string|null
     */
    public function getSectionPosition()
    {
        return $this->container['section_position'];
    }

    /**
     * Sets section_position
     *
     * @param string|null $section_position section_position
     *
     * @return self
     */
    public function setSectionPosition($section_position)
    {
        $this->container['section_position'] = $section_position;

        return $this;
    }

    /**
     * Gets margin_top
     *
     * @return string|null
     */
    public function getMarginTop()
    {
        return $this->container['margin_top'];
    }

    /**
     * Sets margin_top
     *
     * @param string|null $margin_top margin_top
     *
     * @return self
     */
    public function setMarginTop($margin_top)
    {
        $this->container['margin_top'] = $margin_top;

        return $this;
    }

    /**
     * Gets margin_bottom
     *
     * @return string|null
     */
    public function getMarginBottom()
    {
        return $this->container['margin_bottom'];
    }

    /**
     * Sets margin_bottom
     *
     * @param string|null $margin_bottom margin_bottom
     *
     * @return self
     */
    public function setMarginBottom($margin_bottom)
    {
        $this->container['margin_bottom'] = $margin_bottom;

        return $this;
    }

    /**
     * Gets margin_left
     *
     * @return string|null
     */
    public function getMarginLeft()
    {
        return $this->container['margin_left'];
    }

    /**
     * Sets margin_left
     *
     * @param string|null $margin_left margin_left
     *
     * @return self
     */
    public function setMarginLeft($margin_left)
    {
        $this->container['margin_left'] = $margin_left;

        return $this;
    }

    /**
     * Gets margin_right
     *
     * @return string|null
     */
    public function getMarginRight()
    {
        return $this->container['margin_right'];
    }

    /**
     * Sets margin_right
     *
     * @param string|null $margin_right margin_right
     *
     * @return self
     */
    public function setMarginRight($margin_right)
    {
        $this->container['margin_right'] = $margin_right;

        return $this;
    }

    /**
     * Gets background_color
     *
     * @return string|null
     */
    public function getBackgroundColor()
    {
        return $this->container['background_color'];
    }

    /**
     * Sets background_color
     *
     * @param string|null $background_color background_color
     *
     * @return self
     */
    public function setBackgroundColor($background_color)
    {
        $this->container['background_color'] = $background_color;

        return $this;
    }

    /**
     * Gets background_media_id
     *
     * @return string|null
     */
    public function getBackgroundMediaId()
    {
        return $this->container['background_media_id'];
    }

    /**
     * Sets background_media_id
     *
     * @param string|null $background_media_id background_media_id
     *
     * @return self
     */
    public function setBackgroundMediaId($background_media_id)
    {

        if (!is_null($background_media_id) && (!preg_match("/^[0-9a-f]{32}$/", $background_media_id))) {
            throw new \InvalidArgumentException("invalid value for $background_media_id when calling CmsBlock., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['background_media_id'] = $background_media_id;

        return $this;
    }

    /**
     * Gets background_media_mode
     *
     * @return string|null
     */
    public function getBackgroundMediaMode()
    {
        return $this->container['background_media_mode'];
    }

    /**
     * Sets background_media_mode
     *
     * @param string|null $background_media_mode background_media_mode
     *
     * @return self
     */
    public function setBackgroundMediaMode($background_media_mode)
    {
        $this->container['background_media_mode'] = $background_media_mode;

        return $this;
    }

    /**
     * Gets css_class
     *
     * @return string|null
     */
    public function getCssClass()
    {
        return $this->container['css_class'];
    }

    /**
     * Sets css_class
     *
     * @param string|null $css_class css_class
     *
     * @return self
     */
    public function setCssClass($css_class)
    {
        $this->container['css_class'] = $css_class;

        return $this;
    }

    /**
     * Gets section_id
     *
     * @return string
     */
    public function getSectionId()
    {
        return $this->container['section_id'];
    }

    /**
     * Sets section_id
     *
     * @param string $section_id section_id
     *
     * @return self
     */
    public function setSectionId($section_id)
    {

        if ((!preg_match("/^[0-9a-f]{32}$/", $section_id))) {
            throw new \InvalidArgumentException("invalid value for $section_id when calling CmsBlock., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['section_id'] = $section_id;

        return $this;
    }

    /**
     * Gets custom_fields
     *
     * @return object|null
     */
    public function getCustomFields()
    {
        return $this->container['custom_fields'];
    }

    /**
     * Sets custom_fields
     *
     * @param object|null $custom_fields custom_fields
     *
     * @return self
     */
    public function setCustomFields($custom_fields)
    {
        $this->container['custom_fields'] = $custom_fields;

        return $this;
    }

    /**
     * Gets version_id
     *
     * @return string|null
     */
    public function getVersionId()
    {
        return $this->container['version_id'];
    }

    /**
     * Sets version_id
     *
     * @param string|null $version_id version_id
     *
     * @return self
     */
    public function setVersionId($version_id)
    {

        if (!is_null($version_id) && (!preg_match("/^[0-9a-f]{32}$/", $version_id))) {
            throw new \InvalidArgumentException("invalid value for $version_id when calling CmsBlock., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['version_id'] = $version_id;

        return $this;
    }

    /**
     * Gets cms_section_version_id
     *
     * @return string|null
     */
    public function getCmsSectionVersionId()
    {
        return $this->container['cms_section_version_id'];
    }

    /**
     * Sets cms_section_version_id
     *
     * @param string|null $cms_section_version_id cms_section_version_id
     *
     * @return self
     */
    public function setCmsSectionVersionId($cms_section_version_id)
    {

        if (!is_null($cms_section_version_id) && (!preg_match("/^[0-9a-f]{32}$/", $cms_section_version_id))) {
            throw new \InvalidArgumentException("invalid value for $cms_section_version_id when calling CmsBlock., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['cms_section_version_id'] = $cms_section_version_id;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets section
     *
     * @return \OpenAPI\Client\Model\CmsSection|null
     */
    public function getSection()
    {
        return $this->container['section'];
    }

    /**
     * Sets section
     *
     * @param \OpenAPI\Client\Model\CmsSection|null $section section
     *
     * @return self
     */
    public function setSection($section)
    {
        $this->container['section'] = $section;

        return $this;
    }

    /**
     * Gets background_media
     *
     * @return \OpenAPI\Client\Model\Media|null
     */
    public function getBackgroundMedia()
    {
        return $this->container['background_media'];
    }

    /**
     * Sets background_media
     *
     * @param \OpenAPI\Client\Model\Media|null $background_media background_media
     *
     * @return self
     */
    public function setBackgroundMedia($background_media)
    {
        $this->container['background_media'] = $background_media;

        return $this;
    }

    /**
     * Gets slots
     *
     * @return \OpenAPI\Client\Model\CmsSlot|null
     */
    public function getSlots()
    {
        return $this->container['slots'];
    }

    /**
     * Sets slots
     *
     * @param \OpenAPI\Client\Model\CmsSlot|null $slots slots
     *
     * @return self
     */
    public function setSlots($slots)
    {
        $this->container['slots'] = $slots;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


