<?php
/**
 * Country
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shopware Admin API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Admin API.  For a better overview, all CRUD-endpoints are hidden by default. If you want to show also CRUD-endpoints add the query parameter `type=jsonapi`.
 *
 * The version of the OpenAPI document: 6.4.7.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Country Class Doc Comment
 *
 * @category Class
 * @description Added since version: 6.0.0.0
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class Country implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Country';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'name' => 'string',
        'iso' => 'string',
        'position' => 'int',
        'tax_free' => 'bool',
        'active' => 'bool',
        'shipping_available' => 'bool',
        'iso3' => 'string',
        'display_state_in_registration' => 'bool',
        'force_state_in_registration' => 'bool',
        'company_tax_free' => 'bool',
        'check_vat_id_pattern' => 'bool',
        'vat_id_required' => 'bool',
        'vat_id_pattern' => 'string',
        'custom_fields' => 'object',
        'customer_tax' => '\OpenAPI\Client\Model\CountryCustomerTax',
        'company_tax' => '\OpenAPI\Client\Model\CountryCustomerTax',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'translated' => 'object',
        'states' => '\OpenAPI\Client\Model\CountryState',
        'customer_addresses' => '\OpenAPI\Client\Model\CustomerAddress',
        'order_addresses' => '\OpenAPI\Client\Model\OrderAddress',
        'sales_channel_default_assignments' => '\OpenAPI\Client\Model\SalesChannel',
        'sales_channels' => '\OpenAPI\Client\Model\SalesChannel',
        'tax_rules' => '\OpenAPI\Client\Model\TaxRule',
        'currency_country_roundings' => '\OpenAPI\Client\Model\CurrencyCountryRounding'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'name' => null,
        'iso' => null,
        'position' => 'int64',
        'tax_free' => null,
        'active' => null,
        'shipping_available' => null,
        'iso3' => null,
        'display_state_in_registration' => null,
        'force_state_in_registration' => null,
        'company_tax_free' => null,
        'check_vat_id_pattern' => null,
        'vat_id_required' => null,
        'vat_id_pattern' => null,
        'custom_fields' => null,
        'customer_tax' => null,
        'company_tax' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'translated' => null,
        'states' => null,
        'customer_addresses' => null,
        'order_addresses' => null,
        'sales_channel_default_assignments' => null,
        'sales_channels' => null,
        'tax_rules' => null,
        'currency_country_roundings' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'iso' => 'iso',
        'position' => 'position',
        'tax_free' => 'taxFree',
        'active' => 'active',
        'shipping_available' => 'shippingAvailable',
        'iso3' => 'iso3',
        'display_state_in_registration' => 'displayStateInRegistration',
        'force_state_in_registration' => 'forceStateInRegistration',
        'company_tax_free' => 'companyTaxFree',
        'check_vat_id_pattern' => 'checkVatIdPattern',
        'vat_id_required' => 'vatIdRequired',
        'vat_id_pattern' => 'vatIdPattern',
        'custom_fields' => 'customFields',
        'customer_tax' => 'customerTax',
        'company_tax' => 'companyTax',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt',
        'translated' => 'translated',
        'states' => 'states',
        'customer_addresses' => 'customerAddresses',
        'order_addresses' => 'orderAddresses',
        'sales_channel_default_assignments' => 'salesChannelDefaultAssignments',
        'sales_channels' => 'salesChannels',
        'tax_rules' => 'taxRules',
        'currency_country_roundings' => 'currencyCountryRoundings'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'iso' => 'setIso',
        'position' => 'setPosition',
        'tax_free' => 'setTaxFree',
        'active' => 'setActive',
        'shipping_available' => 'setShippingAvailable',
        'iso3' => 'setIso3',
        'display_state_in_registration' => 'setDisplayStateInRegistration',
        'force_state_in_registration' => 'setForceStateInRegistration',
        'company_tax_free' => 'setCompanyTaxFree',
        'check_vat_id_pattern' => 'setCheckVatIdPattern',
        'vat_id_required' => 'setVatIdRequired',
        'vat_id_pattern' => 'setVatIdPattern',
        'custom_fields' => 'setCustomFields',
        'customer_tax' => 'setCustomerTax',
        'company_tax' => 'setCompanyTax',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'translated' => 'setTranslated',
        'states' => 'setStates',
        'customer_addresses' => 'setCustomerAddresses',
        'order_addresses' => 'setOrderAddresses',
        'sales_channel_default_assignments' => 'setSalesChannelDefaultAssignments',
        'sales_channels' => 'setSalesChannels',
        'tax_rules' => 'setTaxRules',
        'currency_country_roundings' => 'setCurrencyCountryRoundings'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'iso' => 'getIso',
        'position' => 'getPosition',
        'tax_free' => 'getTaxFree',
        'active' => 'getActive',
        'shipping_available' => 'getShippingAvailable',
        'iso3' => 'getIso3',
        'display_state_in_registration' => 'getDisplayStateInRegistration',
        'force_state_in_registration' => 'getForceStateInRegistration',
        'company_tax_free' => 'getCompanyTaxFree',
        'check_vat_id_pattern' => 'getCheckVatIdPattern',
        'vat_id_required' => 'getVatIdRequired',
        'vat_id_pattern' => 'getVatIdPattern',
        'custom_fields' => 'getCustomFields',
        'customer_tax' => 'getCustomerTax',
        'company_tax' => 'getCompanyTax',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'translated' => 'getTranslated',
        'states' => 'getStates',
        'customer_addresses' => 'getCustomerAddresses',
        'order_addresses' => 'getOrderAddresses',
        'sales_channel_default_assignments' => 'getSalesChannelDefaultAssignments',
        'sales_channels' => 'getSalesChannels',
        'tax_rules' => 'getTaxRules',
        'currency_country_roundings' => 'getCurrencyCountryRoundings'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['iso'] = $data['iso'] ?? null;
        $this->container['position'] = $data['position'] ?? null;
        $this->container['tax_free'] = $data['tax_free'] ?? null;
        $this->container['active'] = $data['active'] ?? null;
        $this->container['shipping_available'] = $data['shipping_available'] ?? null;
        $this->container['iso3'] = $data['iso3'] ?? null;
        $this->container['display_state_in_registration'] = $data['display_state_in_registration'] ?? null;
        $this->container['force_state_in_registration'] = $data['force_state_in_registration'] ?? null;
        $this->container['company_tax_free'] = $data['company_tax_free'] ?? null;
        $this->container['check_vat_id_pattern'] = $data['check_vat_id_pattern'] ?? null;
        $this->container['vat_id_required'] = $data['vat_id_required'] ?? null;
        $this->container['vat_id_pattern'] = $data['vat_id_pattern'] ?? null;
        $this->container['custom_fields'] = $data['custom_fields'] ?? null;
        $this->container['customer_tax'] = $data['customer_tax'] ?? null;
        $this->container['company_tax'] = $data['company_tax'] ?? null;
        $this->container['created_at'] = $data['created_at'] ?? null;
        $this->container['updated_at'] = $data['updated_at'] ?? null;
        $this->container['translated'] = $data['translated'] ?? null;
        $this->container['states'] = $data['states'] ?? null;
        $this->container['customer_addresses'] = $data['customer_addresses'] ?? null;
        $this->container['order_addresses'] = $data['order_addresses'] ?? null;
        $this->container['sales_channel_default_assignments'] = $data['sales_channel_default_assignments'] ?? null;
        $this->container['sales_channels'] = $data['sales_channels'] ?? null;
        $this->container['tax_rules'] = $data['tax_rules'] ?? null;
        $this->container['currency_country_roundings'] = $data['currency_country_roundings'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['id']) && !preg_match("/^[0-9a-f]{32}$/", $this->container['id'])) {
            $invalidProperties[] = "invalid value for 'id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {

        if (!is_null($id) && (!preg_match("/^[0-9a-f]{32}$/", $id))) {
            throw new \InvalidArgumentException("invalid value for $id when calling Country., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets iso
     *
     * @return string|null
     */
    public function getIso()
    {
        return $this->container['iso'];
    }

    /**
     * Sets iso
     *
     * @param string|null $iso iso
     *
     * @return self
     */
    public function setIso($iso)
    {
        $this->container['iso'] = $iso;

        return $this;
    }

    /**
     * Gets position
     *
     * @return int|null
     */
    public function getPosition()
    {
        return $this->container['position'];
    }

    /**
     * Sets position
     *
     * @param int|null $position position
     *
     * @return self
     */
    public function setPosition($position)
    {
        $this->container['position'] = $position;

        return $this;
    }

    /**
     * Gets tax_free
     *
     * @return bool|null
     * @deprecated
     */
    public function getTaxFree()
    {
        return $this->container['tax_free'];
    }

    /**
     * Sets tax_free
     *
     * @param bool|null $tax_free tax_free
     *
     * @return self
     * @deprecated
     */
    public function setTaxFree($tax_free)
    {
        $this->container['tax_free'] = $tax_free;

        return $this;
    }

    /**
     * Gets active
     *
     * @return bool|null
     */
    public function getActive()
    {
        return $this->container['active'];
    }

    /**
     * Sets active
     *
     * @param bool|null $active active
     *
     * @return self
     */
    public function setActive($active)
    {
        $this->container['active'] = $active;

        return $this;
    }

    /**
     * Gets shipping_available
     *
     * @return bool|null
     */
    public function getShippingAvailable()
    {
        return $this->container['shipping_available'];
    }

    /**
     * Sets shipping_available
     *
     * @param bool|null $shipping_available shipping_available
     *
     * @return self
     */
    public function setShippingAvailable($shipping_available)
    {
        $this->container['shipping_available'] = $shipping_available;

        return $this;
    }

    /**
     * Gets iso3
     *
     * @return string|null
     */
    public function getIso3()
    {
        return $this->container['iso3'];
    }

    /**
     * Sets iso3
     *
     * @param string|null $iso3 iso3
     *
     * @return self
     */
    public function setIso3($iso3)
    {
        $this->container['iso3'] = $iso3;

        return $this;
    }

    /**
     * Gets display_state_in_registration
     *
     * @return bool|null
     */
    public function getDisplayStateInRegistration()
    {
        return $this->container['display_state_in_registration'];
    }

    /**
     * Sets display_state_in_registration
     *
     * @param bool|null $display_state_in_registration display_state_in_registration
     *
     * @return self
     */
    public function setDisplayStateInRegistration($display_state_in_registration)
    {
        $this->container['display_state_in_registration'] = $display_state_in_registration;

        return $this;
    }

    /**
     * Gets force_state_in_registration
     *
     * @return bool|null
     */
    public function getForceStateInRegistration()
    {
        return $this->container['force_state_in_registration'];
    }

    /**
     * Sets force_state_in_registration
     *
     * @param bool|null $force_state_in_registration force_state_in_registration
     *
     * @return self
     */
    public function setForceStateInRegistration($force_state_in_registration)
    {
        $this->container['force_state_in_registration'] = $force_state_in_registration;

        return $this;
    }

    /**
     * Gets company_tax_free
     *
     * @return bool|null
     * @deprecated
     */
    public function getCompanyTaxFree()
    {
        return $this->container['company_tax_free'];
    }

    /**
     * Sets company_tax_free
     *
     * @param bool|null $company_tax_free company_tax_free
     *
     * @return self
     * @deprecated
     */
    public function setCompanyTaxFree($company_tax_free)
    {
        $this->container['company_tax_free'] = $company_tax_free;

        return $this;
    }

    /**
     * Gets check_vat_id_pattern
     *
     * @return bool|null
     */
    public function getCheckVatIdPattern()
    {
        return $this->container['check_vat_id_pattern'];
    }

    /**
     * Sets check_vat_id_pattern
     *
     * @param bool|null $check_vat_id_pattern check_vat_id_pattern
     *
     * @return self
     */
    public function setCheckVatIdPattern($check_vat_id_pattern)
    {
        $this->container['check_vat_id_pattern'] = $check_vat_id_pattern;

        return $this;
    }

    /**
     * Gets vat_id_required
     *
     * @return bool|null
     */
    public function getVatIdRequired()
    {
        return $this->container['vat_id_required'];
    }

    /**
     * Sets vat_id_required
     *
     * @param bool|null $vat_id_required vat_id_required
     *
     * @return self
     */
    public function setVatIdRequired($vat_id_required)
    {
        $this->container['vat_id_required'] = $vat_id_required;

        return $this;
    }

    /**
     * Gets vat_id_pattern
     *
     * @return string|null
     */
    public function getVatIdPattern()
    {
        return $this->container['vat_id_pattern'];
    }

    /**
     * Sets vat_id_pattern
     *
     * @param string|null $vat_id_pattern vat_id_pattern
     *
     * @return self
     */
    public function setVatIdPattern($vat_id_pattern)
    {
        $this->container['vat_id_pattern'] = $vat_id_pattern;

        return $this;
    }

    /**
     * Gets custom_fields
     *
     * @return object|null
     */
    public function getCustomFields()
    {
        return $this->container['custom_fields'];
    }

    /**
     * Sets custom_fields
     *
     * @param object|null $custom_fields custom_fields
     *
     * @return self
     */
    public function setCustomFields($custom_fields)
    {
        $this->container['custom_fields'] = $custom_fields;

        return $this;
    }

    /**
     * Gets customer_tax
     *
     * @return \OpenAPI\Client\Model\CountryCustomerTax|null
     */
    public function getCustomerTax()
    {
        return $this->container['customer_tax'];
    }

    /**
     * Sets customer_tax
     *
     * @param \OpenAPI\Client\Model\CountryCustomerTax|null $customer_tax customer_tax
     *
     * @return self
     */
    public function setCustomerTax($customer_tax)
    {
        $this->container['customer_tax'] = $customer_tax;

        return $this;
    }

    /**
     * Gets company_tax
     *
     * @return \OpenAPI\Client\Model\CountryCustomerTax|null
     */
    public function getCompanyTax()
    {
        return $this->container['company_tax'];
    }

    /**
     * Sets company_tax
     *
     * @param \OpenAPI\Client\Model\CountryCustomerTax|null $company_tax company_tax
     *
     * @return self
     */
    public function setCompanyTax($company_tax)
    {
        $this->container['company_tax'] = $company_tax;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets translated
     *
     * @return object|null
     */
    public function getTranslated()
    {
        return $this->container['translated'];
    }

    /**
     * Sets translated
     *
     * @param object|null $translated translated
     *
     * @return self
     */
    public function setTranslated($translated)
    {
        $this->container['translated'] = $translated;

        return $this;
    }

    /**
     * Gets states
     *
     * @return \OpenAPI\Client\Model\CountryState|null
     */
    public function getStates()
    {
        return $this->container['states'];
    }

    /**
     * Sets states
     *
     * @param \OpenAPI\Client\Model\CountryState|null $states states
     *
     * @return self
     */
    public function setStates($states)
    {
        $this->container['states'] = $states;

        return $this;
    }

    /**
     * Gets customer_addresses
     *
     * @return \OpenAPI\Client\Model\CustomerAddress|null
     */
    public function getCustomerAddresses()
    {
        return $this->container['customer_addresses'];
    }

    /**
     * Sets customer_addresses
     *
     * @param \OpenAPI\Client\Model\CustomerAddress|null $customer_addresses customer_addresses
     *
     * @return self
     */
    public function setCustomerAddresses($customer_addresses)
    {
        $this->container['customer_addresses'] = $customer_addresses;

        return $this;
    }

    /**
     * Gets order_addresses
     *
     * @return \OpenAPI\Client\Model\OrderAddress|null
     */
    public function getOrderAddresses()
    {
        return $this->container['order_addresses'];
    }

    /**
     * Sets order_addresses
     *
     * @param \OpenAPI\Client\Model\OrderAddress|null $order_addresses order_addresses
     *
     * @return self
     */
    public function setOrderAddresses($order_addresses)
    {
        $this->container['order_addresses'] = $order_addresses;

        return $this;
    }

    /**
     * Gets sales_channel_default_assignments
     *
     * @return \OpenAPI\Client\Model\SalesChannel|null
     */
    public function getSalesChannelDefaultAssignments()
    {
        return $this->container['sales_channel_default_assignments'];
    }

    /**
     * Sets sales_channel_default_assignments
     *
     * @param \OpenAPI\Client\Model\SalesChannel|null $sales_channel_default_assignments sales_channel_default_assignments
     *
     * @return self
     */
    public function setSalesChannelDefaultAssignments($sales_channel_default_assignments)
    {
        $this->container['sales_channel_default_assignments'] = $sales_channel_default_assignments;

        return $this;
    }

    /**
     * Gets sales_channels
     *
     * @return \OpenAPI\Client\Model\SalesChannel|null
     */
    public function getSalesChannels()
    {
        return $this->container['sales_channels'];
    }

    /**
     * Sets sales_channels
     *
     * @param \OpenAPI\Client\Model\SalesChannel|null $sales_channels sales_channels
     *
     * @return self
     */
    public function setSalesChannels($sales_channels)
    {
        $this->container['sales_channels'] = $sales_channels;

        return $this;
    }

    /**
     * Gets tax_rules
     *
     * @return \OpenAPI\Client\Model\TaxRule|null
     */
    public function getTaxRules()
    {
        return $this->container['tax_rules'];
    }

    /**
     * Sets tax_rules
     *
     * @param \OpenAPI\Client\Model\TaxRule|null $tax_rules tax_rules
     *
     * @return self
     */
    public function setTaxRules($tax_rules)
    {
        $this->container['tax_rules'] = $tax_rules;

        return $this;
    }

    /**
     * Gets currency_country_roundings
     *
     * @return \OpenAPI\Client\Model\CurrencyCountryRounding|null
     */
    public function getCurrencyCountryRoundings()
    {
        return $this->container['currency_country_roundings'];
    }

    /**
     * Sets currency_country_roundings
     *
     * @param \OpenAPI\Client\Model\CurrencyCountryRounding|null $currency_country_roundings currency_country_roundings
     *
     * @return self
     */
    public function setCurrencyCountryRoundings($currency_country_roundings)
    {
        $this->container['currency_country_roundings'] = $currency_country_roundings;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


