<?php
/**
 * ShippingMethodPrice
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shopware Admin API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Admin API.  For a better overview, all CRUD-endpoints are hidden by default. If you want to show also CRUD-endpoints add the query parameter `type=jsonapi`.
 *
 * The version of the OpenAPI document: 6.4.7.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ShippingMethodPrice Class Doc Comment
 *
 * @category Class
 * @description Added since version: 6.0.0.0
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class ShippingMethodPrice implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ShippingMethodPrice';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'shipping_method_id' => 'string',
        'rule_id' => 'string',
        'calculation' => 'int',
        'calculation_rule_id' => 'string',
        'quantity_start' => 'float',
        'quantity_end' => 'float',
        'currency_price' => 'object',
        'custom_fields' => 'object',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'shipping_method' => '\OpenAPI\Client\Model\ShippingMethod',
        'rule' => '\OpenAPI\Client\Model\Rule',
        'calculation_rule' => '\OpenAPI\Client\Model\Rule'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'shipping_method_id' => null,
        'rule_id' => null,
        'calculation' => 'int64',
        'calculation_rule_id' => null,
        'quantity_start' => 'float',
        'quantity_end' => 'float',
        'currency_price' => null,
        'custom_fields' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'shipping_method' => null,
        'rule' => null,
        'calculation_rule' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'shipping_method_id' => 'shippingMethodId',
        'rule_id' => 'ruleId',
        'calculation' => 'calculation',
        'calculation_rule_id' => 'calculationRuleId',
        'quantity_start' => 'quantityStart',
        'quantity_end' => 'quantityEnd',
        'currency_price' => 'currencyPrice',
        'custom_fields' => 'customFields',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt',
        'shipping_method' => 'shippingMethod',
        'rule' => 'rule',
        'calculation_rule' => 'calculationRule'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'shipping_method_id' => 'setShippingMethodId',
        'rule_id' => 'setRuleId',
        'calculation' => 'setCalculation',
        'calculation_rule_id' => 'setCalculationRuleId',
        'quantity_start' => 'setQuantityStart',
        'quantity_end' => 'setQuantityEnd',
        'currency_price' => 'setCurrencyPrice',
        'custom_fields' => 'setCustomFields',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'shipping_method' => 'setShippingMethod',
        'rule' => 'setRule',
        'calculation_rule' => 'setCalculationRule'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'shipping_method_id' => 'getShippingMethodId',
        'rule_id' => 'getRuleId',
        'calculation' => 'getCalculation',
        'calculation_rule_id' => 'getCalculationRuleId',
        'quantity_start' => 'getQuantityStart',
        'quantity_end' => 'getQuantityEnd',
        'currency_price' => 'getCurrencyPrice',
        'custom_fields' => 'getCustomFields',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'shipping_method' => 'getShippingMethod',
        'rule' => 'getRule',
        'calculation_rule' => 'getCalculationRule'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['shipping_method_id'] = $data['shipping_method_id'] ?? null;
        $this->container['rule_id'] = $data['rule_id'] ?? null;
        $this->container['calculation'] = $data['calculation'] ?? null;
        $this->container['calculation_rule_id'] = $data['calculation_rule_id'] ?? null;
        $this->container['quantity_start'] = $data['quantity_start'] ?? null;
        $this->container['quantity_end'] = $data['quantity_end'] ?? null;
        $this->container['currency_price'] = $data['currency_price'] ?? null;
        $this->container['custom_fields'] = $data['custom_fields'] ?? null;
        $this->container['created_at'] = $data['created_at'] ?? null;
        $this->container['updated_at'] = $data['updated_at'] ?? null;
        $this->container['shipping_method'] = $data['shipping_method'] ?? null;
        $this->container['rule'] = $data['rule'] ?? null;
        $this->container['calculation_rule'] = $data['calculation_rule'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['id']) && !preg_match("/^[0-9a-f]{32}$/", $this->container['id'])) {
            $invalidProperties[] = "invalid value for 'id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if ($this->container['shipping_method_id'] === null) {
            $invalidProperties[] = "'shipping_method_id' can't be null";
        }
        if (!preg_match("/^[0-9a-f]{32}$/", $this->container['shipping_method_id'])) {
            $invalidProperties[] = "invalid value for 'shipping_method_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if (!is_null($this->container['rule_id']) && !preg_match("/^[0-9a-f]{32}$/", $this->container['rule_id'])) {
            $invalidProperties[] = "invalid value for 'rule_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if (!is_null($this->container['calculation_rule_id']) && !preg_match("/^[0-9a-f]{32}$/", $this->container['calculation_rule_id'])) {
            $invalidProperties[] = "invalid value for 'calculation_rule_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {

        if (!is_null($id) && (!preg_match("/^[0-9a-f]{32}$/", $id))) {
            throw new \InvalidArgumentException("invalid value for $id when calling ShippingMethodPrice., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets shipping_method_id
     *
     * @return string
     */
    public function getShippingMethodId()
    {
        return $this->container['shipping_method_id'];
    }

    /**
     * Sets shipping_method_id
     *
     * @param string $shipping_method_id shipping_method_id
     *
     * @return self
     */
    public function setShippingMethodId($shipping_method_id)
    {

        if ((!preg_match("/^[0-9a-f]{32}$/", $shipping_method_id))) {
            throw new \InvalidArgumentException("invalid value for $shipping_method_id when calling ShippingMethodPrice., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['shipping_method_id'] = $shipping_method_id;

        return $this;
    }

    /**
     * Gets rule_id
     *
     * @return string|null
     */
    public function getRuleId()
    {
        return $this->container['rule_id'];
    }

    /**
     * Sets rule_id
     *
     * @param string|null $rule_id rule_id
     *
     * @return self
     */
    public function setRuleId($rule_id)
    {

        if (!is_null($rule_id) && (!preg_match("/^[0-9a-f]{32}$/", $rule_id))) {
            throw new \InvalidArgumentException("invalid value for $rule_id when calling ShippingMethodPrice., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['rule_id'] = $rule_id;

        return $this;
    }

    /**
     * Gets calculation
     *
     * @return int|null
     */
    public function getCalculation()
    {
        return $this->container['calculation'];
    }

    /**
     * Sets calculation
     *
     * @param int|null $calculation calculation
     *
     * @return self
     */
    public function setCalculation($calculation)
    {
        $this->container['calculation'] = $calculation;

        return $this;
    }

    /**
     * Gets calculation_rule_id
     *
     * @return string|null
     */
    public function getCalculationRuleId()
    {
        return $this->container['calculation_rule_id'];
    }

    /**
     * Sets calculation_rule_id
     *
     * @param string|null $calculation_rule_id calculation_rule_id
     *
     * @return self
     */
    public function setCalculationRuleId($calculation_rule_id)
    {

        if (!is_null($calculation_rule_id) && (!preg_match("/^[0-9a-f]{32}$/", $calculation_rule_id))) {
            throw new \InvalidArgumentException("invalid value for $calculation_rule_id when calling ShippingMethodPrice., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['calculation_rule_id'] = $calculation_rule_id;

        return $this;
    }

    /**
     * Gets quantity_start
     *
     * @return float|null
     */
    public function getQuantityStart()
    {
        return $this->container['quantity_start'];
    }

    /**
     * Sets quantity_start
     *
     * @param float|null $quantity_start quantity_start
     *
     * @return self
     */
    public function setQuantityStart($quantity_start)
    {
        $this->container['quantity_start'] = $quantity_start;

        return $this;
    }

    /**
     * Gets quantity_end
     *
     * @return float|null
     */
    public function getQuantityEnd()
    {
        return $this->container['quantity_end'];
    }

    /**
     * Sets quantity_end
     *
     * @param float|null $quantity_end quantity_end
     *
     * @return self
     */
    public function setQuantityEnd($quantity_end)
    {
        $this->container['quantity_end'] = $quantity_end;

        return $this;
    }

    /**
     * Gets currency_price
     *
     * @return object|null
     */
    public function getCurrencyPrice()
    {
        return $this->container['currency_price'];
    }

    /**
     * Sets currency_price
     *
     * @param object|null $currency_price currency_price
     *
     * @return self
     */
    public function setCurrencyPrice($currency_price)
    {
        $this->container['currency_price'] = $currency_price;

        return $this;
    }

    /**
     * Gets custom_fields
     *
     * @return object|null
     */
    public function getCustomFields()
    {
        return $this->container['custom_fields'];
    }

    /**
     * Sets custom_fields
     *
     * @param object|null $custom_fields custom_fields
     *
     * @return self
     */
    public function setCustomFields($custom_fields)
    {
        $this->container['custom_fields'] = $custom_fields;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets shipping_method
     *
     * @return \OpenAPI\Client\Model\ShippingMethod|null
     */
    public function getShippingMethod()
    {
        return $this->container['shipping_method'];
    }

    /**
     * Sets shipping_method
     *
     * @param \OpenAPI\Client\Model\ShippingMethod|null $shipping_method shipping_method
     *
     * @return self
     */
    public function setShippingMethod($shipping_method)
    {
        $this->container['shipping_method'] = $shipping_method;

        return $this;
    }

    /**
     * Gets rule
     *
     * @return \OpenAPI\Client\Model\Rule|null
     */
    public function getRule()
    {
        return $this->container['rule'];
    }

    /**
     * Sets rule
     *
     * @param \OpenAPI\Client\Model\Rule|null $rule rule
     *
     * @return self
     */
    public function setRule($rule)
    {
        $this->container['rule'] = $rule;

        return $this;
    }

    /**
     * Gets calculation_rule
     *
     * @return \OpenAPI\Client\Model\Rule|null
     */
    public function getCalculationRule()
    {
        return $this->container['calculation_rule'];
    }

    /**
     * Sets calculation_rule
     *
     * @param \OpenAPI\Client\Model\Rule|null $calculation_rule calculation_rule
     *
     * @return self
     */
    public function setCalculationRule($calculation_rule)
    {
        $this->container['calculation_rule'] = $calculation_rule;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


