<?php
/**
 * Theme
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shopware Admin API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Admin API.  For a better overview, all CRUD-endpoints are hidden by default. If you want to show also CRUD-endpoints add the query parameter `type=jsonapi`.
 *
 * The version of the OpenAPI document: 6.4.7.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Theme Class Doc Comment
 *
 * @category Class
 * @description Added since version: 6.0.0.0
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class Theme implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Theme';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'technical_name' => 'string',
        'name' => 'string',
        'author' => 'string',
        'description' => 'string',
        'labels' => 'object',
        'help_texts' => 'object',
        'custom_fields' => 'object',
        'preview_media_id' => 'string',
        'parent_theme_id' => 'string',
        'base_config' => 'object',
        'config_values' => 'object',
        'active' => 'bool',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'translated' => 'object',
        'sales_channels' => '\OpenAPI\Client\Model\SalesChannel',
        'media' => '\OpenAPI\Client\Model\Media',
        'preview_media' => '\OpenAPI\Client\Model\Media',
        'child_themes' => '\OpenAPI\Client\Model\Theme'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'technical_name' => null,
        'name' => null,
        'author' => null,
        'description' => null,
        'labels' => null,
        'help_texts' => null,
        'custom_fields' => null,
        'preview_media_id' => null,
        'parent_theme_id' => null,
        'base_config' => null,
        'config_values' => null,
        'active' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'translated' => null,
        'sales_channels' => null,
        'media' => null,
        'preview_media' => null,
        'child_themes' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'technical_name' => 'technicalName',
        'name' => 'name',
        'author' => 'author',
        'description' => 'description',
        'labels' => 'labels',
        'help_texts' => 'helpTexts',
        'custom_fields' => 'customFields',
        'preview_media_id' => 'previewMediaId',
        'parent_theme_id' => 'parentThemeId',
        'base_config' => 'baseConfig',
        'config_values' => 'configValues',
        'active' => 'active',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt',
        'translated' => 'translated',
        'sales_channels' => 'salesChannels',
        'media' => 'media',
        'preview_media' => 'previewMedia',
        'child_themes' => 'childThemes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'technical_name' => 'setTechnicalName',
        'name' => 'setName',
        'author' => 'setAuthor',
        'description' => 'setDescription',
        'labels' => 'setLabels',
        'help_texts' => 'setHelpTexts',
        'custom_fields' => 'setCustomFields',
        'preview_media_id' => 'setPreviewMediaId',
        'parent_theme_id' => 'setParentThemeId',
        'base_config' => 'setBaseConfig',
        'config_values' => 'setConfigValues',
        'active' => 'setActive',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'translated' => 'setTranslated',
        'sales_channels' => 'setSalesChannels',
        'media' => 'setMedia',
        'preview_media' => 'setPreviewMedia',
        'child_themes' => 'setChildThemes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'technical_name' => 'getTechnicalName',
        'name' => 'getName',
        'author' => 'getAuthor',
        'description' => 'getDescription',
        'labels' => 'getLabels',
        'help_texts' => 'getHelpTexts',
        'custom_fields' => 'getCustomFields',
        'preview_media_id' => 'getPreviewMediaId',
        'parent_theme_id' => 'getParentThemeId',
        'base_config' => 'getBaseConfig',
        'config_values' => 'getConfigValues',
        'active' => 'getActive',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'translated' => 'getTranslated',
        'sales_channels' => 'getSalesChannels',
        'media' => 'getMedia',
        'preview_media' => 'getPreviewMedia',
        'child_themes' => 'getChildThemes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['technical_name'] = $data['technical_name'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['author'] = $data['author'] ?? null;
        $this->container['description'] = $data['description'] ?? null;
        $this->container['labels'] = $data['labels'] ?? null;
        $this->container['help_texts'] = $data['help_texts'] ?? null;
        $this->container['custom_fields'] = $data['custom_fields'] ?? null;
        $this->container['preview_media_id'] = $data['preview_media_id'] ?? null;
        $this->container['parent_theme_id'] = $data['parent_theme_id'] ?? null;
        $this->container['base_config'] = $data['base_config'] ?? null;
        $this->container['config_values'] = $data['config_values'] ?? null;
        $this->container['active'] = $data['active'] ?? null;
        $this->container['created_at'] = $data['created_at'] ?? null;
        $this->container['updated_at'] = $data['updated_at'] ?? null;
        $this->container['translated'] = $data['translated'] ?? null;
        $this->container['sales_channels'] = $data['sales_channels'] ?? null;
        $this->container['media'] = $data['media'] ?? null;
        $this->container['preview_media'] = $data['preview_media'] ?? null;
        $this->container['child_themes'] = $data['child_themes'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['id']) && !preg_match("/^[0-9a-f]{32}$/", $this->container['id'])) {
            $invalidProperties[] = "invalid value for 'id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['author'] === null) {
            $invalidProperties[] = "'author' can't be null";
        }
        if (!is_null($this->container['preview_media_id']) && !preg_match("/^[0-9a-f]{32}$/", $this->container['preview_media_id'])) {
            $invalidProperties[] = "invalid value for 'preview_media_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if (!is_null($this->container['parent_theme_id']) && !preg_match("/^[0-9a-f]{32}$/", $this->container['parent_theme_id'])) {
            $invalidProperties[] = "invalid value for 'parent_theme_id', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if ($this->container['active'] === null) {
            $invalidProperties[] = "'active' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {

        if (!is_null($id) && (!preg_match("/^[0-9a-f]{32}$/", $id))) {
            throw new \InvalidArgumentException("invalid value for $id when calling Theme., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets technical_name
     *
     * @return string|null
     */
    public function getTechnicalName()
    {
        return $this->container['technical_name'];
    }

    /**
     * Sets technical_name
     *
     * @param string|null $technical_name technical_name
     *
     * @return self
     */
    public function setTechnicalName($technical_name)
    {
        $this->container['technical_name'] = $technical_name;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets author
     *
     * @return string
     */
    public function getAuthor()
    {
        return $this->container['author'];
    }

    /**
     * Sets author
     *
     * @param string $author author
     *
     * @return self
     */
    public function setAuthor($author)
    {
        $this->container['author'] = $author;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets labels
     *
     * @return object|null
     */
    public function getLabels()
    {
        return $this->container['labels'];
    }

    /**
     * Sets labels
     *
     * @param object|null $labels labels
     *
     * @return self
     */
    public function setLabels($labels)
    {
        $this->container['labels'] = $labels;

        return $this;
    }

    /**
     * Gets help_texts
     *
     * @return object|null
     */
    public function getHelpTexts()
    {
        return $this->container['help_texts'];
    }

    /**
     * Sets help_texts
     *
     * @param object|null $help_texts help_texts
     *
     * @return self
     */
    public function setHelpTexts($help_texts)
    {
        $this->container['help_texts'] = $help_texts;

        return $this;
    }

    /**
     * Gets custom_fields
     *
     * @return object|null
     */
    public function getCustomFields()
    {
        return $this->container['custom_fields'];
    }

    /**
     * Sets custom_fields
     *
     * @param object|null $custom_fields custom_fields
     *
     * @return self
     */
    public function setCustomFields($custom_fields)
    {
        $this->container['custom_fields'] = $custom_fields;

        return $this;
    }

    /**
     * Gets preview_media_id
     *
     * @return string|null
     */
    public function getPreviewMediaId()
    {
        return $this->container['preview_media_id'];
    }

    /**
     * Sets preview_media_id
     *
     * @param string|null $preview_media_id preview_media_id
     *
     * @return self
     */
    public function setPreviewMediaId($preview_media_id)
    {

        if (!is_null($preview_media_id) && (!preg_match("/^[0-9a-f]{32}$/", $preview_media_id))) {
            throw new \InvalidArgumentException("invalid value for $preview_media_id when calling Theme., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['preview_media_id'] = $preview_media_id;

        return $this;
    }

    /**
     * Gets parent_theme_id
     *
     * @return string|null
     */
    public function getParentThemeId()
    {
        return $this->container['parent_theme_id'];
    }

    /**
     * Sets parent_theme_id
     *
     * @param string|null $parent_theme_id parent_theme_id
     *
     * @return self
     */
    public function setParentThemeId($parent_theme_id)
    {

        if (!is_null($parent_theme_id) && (!preg_match("/^[0-9a-f]{32}$/", $parent_theme_id))) {
            throw new \InvalidArgumentException("invalid value for $parent_theme_id when calling Theme., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['parent_theme_id'] = $parent_theme_id;

        return $this;
    }

    /**
     * Gets base_config
     *
     * @return object|null
     */
    public function getBaseConfig()
    {
        return $this->container['base_config'];
    }

    /**
     * Sets base_config
     *
     * @param object|null $base_config base_config
     *
     * @return self
     */
    public function setBaseConfig($base_config)
    {
        $this->container['base_config'] = $base_config;

        return $this;
    }

    /**
     * Gets config_values
     *
     * @return object|null
     */
    public function getConfigValues()
    {
        return $this->container['config_values'];
    }

    /**
     * Sets config_values
     *
     * @param object|null $config_values config_values
     *
     * @return self
     */
    public function setConfigValues($config_values)
    {
        $this->container['config_values'] = $config_values;

        return $this;
    }

    /**
     * Gets active
     *
     * @return bool
     */
    public function getActive()
    {
        return $this->container['active'];
    }

    /**
     * Sets active
     *
     * @param bool $active active
     *
     * @return self
     */
    public function setActive($active)
    {
        $this->container['active'] = $active;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets translated
     *
     * @return object|null
     */
    public function getTranslated()
    {
        return $this->container['translated'];
    }

    /**
     * Sets translated
     *
     * @param object|null $translated translated
     *
     * @return self
     */
    public function setTranslated($translated)
    {
        $this->container['translated'] = $translated;

        return $this;
    }

    /**
     * Gets sales_channels
     *
     * @return \OpenAPI\Client\Model\SalesChannel|null
     */
    public function getSalesChannels()
    {
        return $this->container['sales_channels'];
    }

    /**
     * Sets sales_channels
     *
     * @param \OpenAPI\Client\Model\SalesChannel|null $sales_channels sales_channels
     *
     * @return self
     */
    public function setSalesChannels($sales_channels)
    {
        $this->container['sales_channels'] = $sales_channels;

        return $this;
    }

    /**
     * Gets media
     *
     * @return \OpenAPI\Client\Model\Media|null
     */
    public function getMedia()
    {
        return $this->container['media'];
    }

    /**
     * Sets media
     *
     * @param \OpenAPI\Client\Model\Media|null $media media
     *
     * @return self
     */
    public function setMedia($media)
    {
        $this->container['media'] = $media;

        return $this;
    }

    /**
     * Gets preview_media
     *
     * @return \OpenAPI\Client\Model\Media|null
     */
    public function getPreviewMedia()
    {
        return $this->container['preview_media'];
    }

    /**
     * Sets preview_media
     *
     * @param \OpenAPI\Client\Model\Media|null $preview_media preview_media
     *
     * @return self
     */
    public function setPreviewMedia($preview_media)
    {
        $this->container['preview_media'] = $preview_media;

        return $this;
    }

    /**
     * Gets child_themes
     *
     * @return \OpenAPI\Client\Model\Theme|null
     */
    public function getChildThemes()
    {
        return $this->container['child_themes'];
    }

    /**
     * Sets child_themes
     *
     * @param \OpenAPI\Client\Model\Theme|null $child_themes child_themes
     *
     * @return self
     */
    public function setChildThemes($child_themes)
    {
        $this->container['child_themes'] = $child_themes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


